LLVM_CONFIG?=llvm-config

ifndef VERBOSE
	QUIET:=@
endif

SRC_DIR ?= $(PWD)
LDFLAGS += $(shell $(LLVM_CONFIG) --ldflags)
COMMON_FLAGS :=
CXXFLAGS += -g $(COMMON_FLAGS) $(shell $(LLVM_CONFIG) --cxxflags)
CPPFLAGS += -g $(shell $(LLVM_CONFIG) --cppflags) -I$(SRC_DIR) -fPIC

ifeq ($(shell uname),Darwin)
	LOADABLE_MODULE_OPTIONS=-bundle -undefined dynamic_lookup
else
	LOADABLE_MODULE_OPTIONS=-shared -Wl,-O1
endif


CC := clang
CXX := clang++
OPT := opt
DIS := llvm-dis
